### ISSUE TITLE
ROS example not working

### ISSUE THREAD

**Issue by DharminB** [meco-group/omg-tools#73]
I am using ROS kinetic and gazebo 7.

After following instructions from `/examples/ros_example/readme.md`, the `catkin_build` exited successfully.
However, `roslaunch p3dx_gazebo gazebo.launch` gives errors and warnings regarding invalid hardware. (Output pasted at the end for single robot)

I was able to replicate this behaviour with multiple install and `catkin_make`. Also, by launching a single robot (commenting other robots in `gazebo.launch`), the errors in launching gazebo remains same.

**Note** : `motionplanner.launch` works without errors and the simulation works as expected. The robots in simulation are able to move.  

**gazebo.launch output for single robot**
```
process[gazebo-1]: started with pid [28429]
process[gazebo_gui-2]: started with pid [28434]
process[robot0/spawn_robot-3]: started with pid [28439]
[ INFO] [1546286019.730004800]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1546286019.732148329]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
SpawnModel script started
[ INFO] [1546286020.014071336]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1546286020.015123395]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[INFO] [1546286020.018061, 0.000000]: Loading model XML from ros parameter
[INFO] [1546286020.022532, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[ INFO] [1546286020.512612992, 0.020800000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1546286020.569295030, 0.032200000]: Physics dynamic reconfigure ready.
[INFO] [1546286020.629762, 0.044000]: Calling service /gazebo/spawn_urdf_model
[ INFO] [1546286020.690448546, 0.056000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[INFO] [1546286021.297719, 0.067800]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1546286021.302038466, 0.067800000]: Laser Plugin: Using the 'robotNamespace' param: '/robot0/'
[ INFO] [1546286021.302117333, 0.067800000]: Starting Laser Plugin (ns = /robot0/)
[ INFO] [1546286021.303929821, 0.067800000]: Laser Plugin (ns = /robot0/)  <tf_prefix_>, set to "/robot0"
[ INFO] [1546286021.318285674, 0.067800000]: Physics dynamic reconfigure ready.
[ INFO] [1546286021.427561951, 0.067800000]: Loading gazebo_ros_control plugin
[ INFO] [1546286021.427719570, 0.067800000]: Starting gazebo_ros_control plugin in namespace: /p3dx
[ INFO] [1546286021.428735040, 0.067800000]: gazebo_ros_control plugin is waiting for model URDF in parameter [/robot_description] on the ROS param server.
[ERROR] [1546286021.530953595, 0.067800000]: No valid hardware interface element found in joint 'base_left_wheel_joint'.
[ERROR] [1546286021.531058333, 0.067800000]: Failed to load joints for transmission 'base_link_left_wheel_trans'.
[ERROR] [1546286021.531110033, 0.067800000]: No valid hardware interface element found in joint 'base_right_wheel_joint'.
[ERROR] [1546286021.531151186, 0.067800000]: Failed to load joints for transmission 'base_link_right_wheel_trans'.
[ INFO] [1546286021.555010095, 0.067800000]: Loaded gazebo_ros_control.
[ INFO] [1546286021.563581982, 0.067800000]: Starting plugin DiffDrive(ns = /robot0//)
[ WARN] [1546286021.563692409, 0.067800000]: DiffDrive(ns = /robot0//): missing <rosDebugLevel> default is na
[ INFO] [1546286021.564703757, 0.067800000]: DiffDrive(ns = /robot0//): <tf_prefix> = /robot0
[ WARN] [1546286021.564906098, 0.067800000]: DiffDrive(ns = /robot0//): missing <publishWheelTF> default is false
[ WARN] [1546286021.564948881, 0.067800000]: DiffDrive(ns = /robot0//): missing <publishOdomTF> default is ture
[ WARN] [1546286021.564978043, 0.067800000]: DiffDrive(ns = /robot0//): missing <publishWheelJointState> default is false
[ WARN] [1546286021.565140982, 0.067800000]: DiffDrive(ns = /robot0//): missing <wheelAcceleration> default is 0
[ WARN] [1546286021.565179224, 0.067800000]: DiffDrive(ns = /robot0//): missing <wheelTorque> default is 5
[ WARN] [1546286021.565289689, 0.067800000]: DiffDrive(ns = /robot0//): missing <odometrySource> default is 1
[ WARN] [1546286021.565389595, 0.067800000]: GazeboRosDiffDrive Plugin (ns = ) missing <publishTf>, defaults to 1
[ INFO] [1546286021.566548514, 0.067800000]: DiffDrive(ns = /robot0//): Try to subscribe to p3dx/cmd_vel
[ INFO] [1546286021.570681760, 0.067800000]: DiffDrive(ns = /robot0//): Subscribe to p3dx/cmd_vel
[ INFO] [1546286021.571670565, 0.067800000]: DiffDrive(ns = /robot0//): Advertise odom on odom 
[robot0/spawn_robot-3] process has finished cleanly
```

**Comment by rubenvanparys** [comment]
If I understand correctly: everything works fine, but you are worried about the errors and warnings during the launching of gazebo?

**Comment by DharminB** [comment]
Exactly

**Comment by rubenvanparys** [comment]
Allright! I have the same issues when launching gazebo. I didn't have time to clear this out, but it doesn't influence the working of the example.

**Comment by wanghuohuo0716** [comment]
you can check [this](https://answers.ros.org/question/292444/gazebo_ros_control-plugin-gazeboroscontrolplugin-missing-legacymodens-defaultrobothwsim/) for gazebo problem, to add     <legacyModeNS>true</legacyModeNS> to fix it

**Comment by Claud1234** [comment]
Hi:
I am using ROS melodic and Gazebo9.
I followed the instruction from README. For four robots(three moving and one as dynamic objects)
When I launched gazebo.launch, had some extra errors complained about 'controller_manager'
`ROS_MASTER_URI=http://localhost:11311

process[gazebo-1]: started with pid [31220]
process[gazebo_gui-2]: started with pid [31224]
process[robot0/spawn_robot-3]: started with pid [31230]
process[robot1/spawn_robot-4]: started with pid [31231]
process[robot2/spawn_robot-5]: started with pid [31232]
process[robobst0/spawn_robot-6]: started with pid [31233]
[ INFO] [1586376445.921374542]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1586376445.922021348]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1586376445.938117081]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1586376445.938726237]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[INFO] [1586376446.319122, 0.000000]: Loading model XML from ros parameter /robot_description
[INFO] [1586376446.324465, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1586376446.341393, 0.000000]: Loading model XML from ros parameter /robot_description
[INFO] [1586376446.346958, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1586376446.348096, 0.000000]: Loading model XML from ros parameter /robot_description
[INFO] [1586376446.353531, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1586376446.363895, 0.000000]: Loading model XML from ros parameter /robot_description
[INFO] [1586376446.369325, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1586376448.732037, 0.000000]: Calling service /gazebo/spawn_urdf_model
[INFO] [1586376448.754612, 0.000000]: Calling service /gazebo/spawn_urdf_model
[INFO] [1586376448.761463, 0.000000]: Calling service /gazebo/spawn_urdf_model
[INFO] [1586376448.776658, 0.000000]: Calling service /gazebo/spawn_urdf_model
[ INFO] [1586376448.839101935, 0.020200000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1586376449.057103239, 0.039400000]: Laser Plugin: Using the 'robotNamespace' param: '/robobst0/'
[ INFO] [1586376449.057143488, 0.039400000]: Starting Laser Plugin (ns = /robobst0/)
[ INFO] [1586376449.057699025, 0.039400000]: Laser Plugin (ns = /robobst0/)  <tf_prefix_>, set to "/robobst0"
[INFO] [1586376449.122451, 0.039400]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1586376449.133151445, 0.039400000]: Loading gazebo_ros_control plugin
[ INFO] [1586376449.133212954, 0.039400000]: Starting gazebo_ros_control plugin in namespace: /p3dx
[ INFO] [1586376449.133472833, 0.039400000]: gazebo_ros_control plugin is waiting for model URDF in parameter [/robot_description] on the ROS param server.
[ERROR] [1586376449.234196146, 0.039400000]: No valid hardware interface element found in joint 'base_left_wheel_joint'.
[ERROR] [1586376449.234215965, 0.039400000]: Failed to load joints for transmission 'base_link_left_wheel_trans'.
[ERROR] [1586376449.234226345, 0.039400000]: No valid hardware interface element found in joint 'base_right_wheel_joint'.
[ERROR] [1586376449.234237255, 0.039400000]: Failed to load joints for transmission 'base_link_right_wheel_trans'.
[ INFO] [1586376449.242260811, 0.039400000]: Loaded gazebo_ros_control.
[ INFO] [1586376449.246134636, 0.039400000]: Starting plugin DiffDrive(ns = /robobst0//)
[ WARN] [1586376449.246163776, 0.039400000]: DiffDrive(ns = /robobst0//): missing <rosDebugLevel> default is na
[ INFO] [1586376449.246410684, 0.039400000]: DiffDrive(ns = /robobst0//): <tf_prefix> = /robobst0
[ WARN] [1586376449.246444064, 0.039400000]: DiffDrive(ns = /robobst0//): missing <publishWheelTF> default is false
[ WARN] [1586376449.246453934, 0.039400000]: DiffDrive(ns = /robobst0//): missing <publishOdomTF> default is true
[ WARN] [1586376449.246465264, 0.039400000]: DiffDrive(ns = /robobst0//): missing <publishWheelJointState> default is false
[ WARN] [1586376449.246499663, 0.039400000]: DiffDrive(ns = /robobst0//): missing <wheelAcceleration> default is 0
[ WARN] [1586376449.246510943, 0.039400000]: DiffDrive(ns = /robobst0//): missing <wheelTorque> default is 5
[ WARN] [1586376449.246543813, 0.039400000]: DiffDrive(ns = /robobst0//): missing <odometrySource> default is 1
[ WARN] [1586376449.246569863, 0.039400000]: GazeboRosDiffDrive Plugin (ns = ) missing <publishTf>, defaults to 1
[ INFO] [1586376449.246862821, 0.039400000]: DiffDrive(ns = /robobst0//): Try to subscribe to p3dx/cmd_vel
[ INFO] [1586376449.247751445, 0.039400000]: DiffDrive(ns = /robobst0//): Subscribe to p3dx/cmd_vel
[ INFO] [1586376449.248021163, 0.039400000]: DiffDrive(ns = /robobst0//): Advertise odom on odom 
[robobst0/spawn_robot-6] process has finished cleanly
log file: /home/claude/.ros/log/7c5857da-79d4-11ea-93a2-00d861a1ed1d/robobst0-spawn_robot-6*.log
[ INFO] [1586376449.561909692, 0.079600000]: Laser Plugin: Using the 'robotNamespace' param: '/robot0/'
[ INFO] [1586376449.561952862, 0.079600000]: Starting Laser Plugin (ns = /robot0/)
[ INFO] [1586376449.562567738, 0.079600000]: Laser Plugin (ns = /robot0/)  <tf_prefix_>, set to "/robot0"
[ INFO] [1586376449.564808773, 0.079600000]: Loading gazebo_ros_control plugin
[ INFO] [1586376449.564837193, 0.079600000]: Starting gazebo_ros_control plugin in namespace: /p3dx
[INFO] [1586376449.564888, 0.079600]: Spawn status: SpawnModel: Successfully spawned entity
[ERROR] [1586376449.665970962, 0.079600000]: No valid hardware interface element found in joint 'base_left_wheel_joint'.
[ERROR] [1586376449.665989132, 0.079600000]: Failed to load joints for transmission 'base_link_left_wheel_trans'.
[ERROR] [1586376449.665999142, 0.079600000]: No valid hardware interface element found in joint 'base_right_wheel_joint'.
[ERROR] [1586376449.666007882, 0.079600000]: Failed to load joints for transmission 'base_link_right_wheel_trans'.
[ERROR] [1586376449.667383002, 0.079600000]: Tried to advertise a service that is already advertised in this node [/p3dx/controller_manager/list_controllers]
[ERROR] [1586376449.667405422, 0.079600000]: Tried to advertise a service that is already advertised in this node [/p3dx/controller_manager/list_controller_types]
[ERROR] [1586376449.667426422, 0.079600000]: Tried to advertise a service that is already advertised in this node [/p3dx/controller_manager/load_controller]
[ERROR] [1586376449.667438562, 0.079600000]: Tried to advertise a service that is already advertised in this node [/p3dx/controller_manager/unload_controller]
[ERROR] [1586376449.667453932, 0.079600000]: Tried to advertise a service that is already advertised in this node [/p3dx/controller_manager/switch_controller]
[ERROR] [1586376449.667468432, 0.079600000]: Tried to advertise a service that is already advertised in this node [/p3dx/controller_manager/reload_controller_libraries]
[ INFO] [1586376449.667491751, 0.079600000]: Loaded gazebo_ros_control.
[ INFO] [1586376449.667558891, 0.079600000]: Starting plugin DiffDrive(ns = /robot0//)
[ WARN] [1586376449.667569891, 0.079600000]: DiffDrive(ns = /robot0//): missing <rosDebugLevel> default is na
[ INFO] [1586376449.667925759, 0.079600000]: DiffDrive(ns = /robot0//): <tf_prefix> = /robot0
[ WARN] [1586376449.667938869, 0.079600000]: DiffDrive(ns = /robot0//): missing <publishWheelTF> default is false
[ WARN] [1586376449.667954238, 0.079600000]: DiffDrive(ns = /robot0//): missing <publishOdomTF> default is true
[ WARN] [1586376449.667965608, 0.079600000]: DiffDrive(ns = /robot0//): missing <publishWheelJointState> default is false
[ WARN] [1586376449.667983048, 0.079600000]: DiffDrive(ns = /robot0//): missing <wheelAcceleration> default is 0
[ WARN] [1586376449.667993408, 0.079600000]: DiffDrive(ns = /robot0//): missing <wheelTorque> default is 5
[ WARN] [1586376449.668008488, 0.079600000]: DiffDrive(ns = /robot0//): missing <odometrySource> default is 1
[ WARN] [1586376449.668021648, 0.079600000]: GazeboRosDiffDrive Plugin (ns = ) missing <publishTf>, defaults to 1
[ INFO] [1586376449.668046788, 0.079600000]: DiffDrive(ns = /robot0//): Try to subscribe to p3dx/cmd_vel
[ INFO] [1586376449.668950662, 0.079600000]: DiffDrive(ns = /robot0//): Subscribe to p3dx/cmd_vel
[ INFO] [1586376449.669158591, 0.079600000]: DiffDrive(ns = /robot0//): Advertise odom on odom 
[robot0/spawn_robot-3] process has finished cleanly
log file: /home/claude/.ros/log/7c5857da-79d4-11ea-93a2-00d861a1ed1d/robot0-spawn_robot-3*.log
[ INFO] [1586376449.978509111, 0.119800000]: Laser Plugin: Using the 'robotNamespace' param: '/robot2/'
[ INFO] [1586376449.978554900, 0.119800000]: Starting Laser Plugin (ns = /robot2/)
[ INFO] [1586376449.979082027, 0.119800000]: Laser Plugin (ns = /robot2/)  <tf_prefix_>, set to "/robot2"
[ INFO] [1586376449.981125773, 0.119800000]: Loading gazebo_ros_control plugin
[ INFO] [1586376449.981152683, 0.119800000]: Starting gazebo_ros_control plugin in namespace: /p3dx
[INFO] [1586376449.981167, 0.119800]: Spawn status: SpawnModel: Successfully spawned entity
[ERROR] [1586376450.082281122, 0.119800000]: No valid hardware interface element found in joint 'base_left_wheel_joint'.
[ERROR] [1586376450.082310162, 0.119800000]: Failed to load joints for transmission 'base_link_left_wheel_trans'.
[ERROR] [1586376450.082321192, 0.119800000]: No valid hardware interface element found in joint 'base_right_wheel_joint'.
[ERROR] [1586376450.082330542, 0.119800000]: Failed to load joints for transmission 'base_link_right_wheel_trans'.
[ERROR] [1586376450.083706943, 0.119800000]: Tried to advertise a service that is already advertised in this node [/p3dx/controller_manager/list_controllers]
[ERROR] [1586376450.083727152, 0.119800000]: Tried to advertise a service that is already advertised in this node [/p3dx/controller_manager/list_controller_types]
[ERROR] [1586376450.083739542, 0.119800000]: Tried to advertise a service that is already advertised in this node [/p3dx/controller_manager/load_controller]
[ERROR] [1586376450.083751992, 0.119800000]: Tried to advertise a service that is already advertised in this node [/p3dx/controller_manager/unload_controller]
[ERROR] [1586376450.083766712, 0.119800000]: Tried to advertise a service that is already advertised in this node [/p3dx/controller_manager/switch_controller]
[ERROR] [1586376450.083783202, 0.119800000]: Tried to advertise a service that is already advertised in this node [/p3dx/controller_manager/reload_controller_libraries]
[ INFO] [1586376450.083806932, 0.119800000]: Loaded gazebo_ros_control.
[ INFO] [1586376450.083941631, 0.119800000]: Starting plugin DiffDrive(ns = /robot2//)
[ WARN] [1586376450.083954501, 0.119800000]: DiffDrive(ns = /robot2//): missing <rosDebugLevel> default is na
[ INFO] [1586376450.084221309, 0.119800000]: DiffDrive(ns = /robot2//): <tf_prefix> = /robot2
[ WARN] [1586376450.084236739, 0.119800000]: DiffDrive(ns = /robot2//): missing <publishWheelTF> default is false
[ WARN] [1586376450.084248579, 0.119800000]: DiffDrive(ns = /robot2//): missing <publishOdomTF> default is true
[ WARN] [1586376450.084260779, 0.119800000]: DiffDrive(ns = /robot2//): missing <publishWheelJointState> default is false
[ WARN] [1586376450.084279169, 0.119800000]: DiffDrive(ns = /robot2//): missing <wheelAcceleration> default is 0
[ WARN] [1586376450.084291759, 0.119800000]: DiffDrive(ns = /robot2//): missing <wheelTorque> default is 5
[ WARN] [1586376450.084306989, 0.119800000]: DiffDrive(ns = /robot2//): missing <odometrySource> default is 1
[ WARN] [1586376450.084324959, 0.119800000]: GazeboRosDiffDrive Plugin (ns = ) missing <publishTf>, defaults to 1
[ INFO] [1586376450.084349388, 0.119800000]: DiffDrive(ns = /robot2//): Try to subscribe to p3dx/cmd_vel
[ INFO] [1586376450.085260342, 0.119800000]: DiffDrive(ns = /robot2//): Subscribe to p3dx/cmd_vel
[ INFO] [1586376450.085509291, 0.119800000]: DiffDrive(ns = /robot2//): Advertise odom on odom 
[robot2/spawn_robot-5] process has finished cleanly
log file: /home/claude/.ros/log/7c5857da-79d4-11ea-93a2-00d861a1ed1d/robot2-spawn_robot-5*.log
[ INFO] [1586376450.395335536, 0.160000000]: Laser Plugin: Using the 'robotNamespace' param: '/robot1/'
[ INFO] [1586376450.395382156, 0.160000000]: Starting Laser Plugin (ns = /robot1/)
[ INFO] [1586376450.396068381, 0.160000000]: Laser Plugin (ns = /robot1/)  <tf_prefix_>, set to "/robot1"
[ INFO] [1586376450.398297817, 0.160000000]: Loading gazebo_ros_control plugin
[ INFO] [1586376450.398324836, 0.160000000]: Starting gazebo_ros_control plugin in namespace: /p3dx
[INFO] [1586376450.398467, 0.160000]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1586376450.403459713, 0.160000000]: Physics dynamic reconfigure ready.
[ERROR] [1586376450.499602634, 0.160000000]: No valid hardware interface element found in joint 'base_left_wheel_joint'.
[ERROR] [1586376450.499628534, 0.160000000]: Failed to load joints for transmission 'base_link_left_wheel_trans'.
[ERROR] [1586376450.499640904, 0.160000000]: No valid hardware interface element found in joint 'base_right_wheel_joint'.
[ERROR] [1586376450.499651744, 0.160000000]: Failed to load joints for transmission 'base_link_right_wheel_trans'.
[ERROR] [1586376450.501031925, 0.160000000]: Tried to advertise a service that is already advertised in this node [/p3dx/controller_manager/list_controllers]
[ERROR] [1586376450.501051944, 0.160000000]: Tried to advertise a service that is already advertised in this node [/p3dx/controller_manager/list_controller_types]
[ERROR] [1586376450.501065094, 0.160000000]: Tried to advertise a service that is already advertised in this node [/p3dx/controller_manager/load_controller]
[ERROR] [1586376450.501082514, 0.160000000]: Tried to advertise a service that is already advertised in this node [/p3dx/controller_manager/unload_controller]
[ERROR] [1586376450.501097214, 0.160000000]: Tried to advertise a service that is already advertised in this node [/p3dx/controller_manager/switch_controller]
[ERROR] [1586376450.501120324, 0.160000000]: Tried to advertise a service that is already advertised in this node [/p3dx/controller_manager/reload_controller_libraries]
[ INFO] [1586376450.501149044, 0.160000000]: Loaded gazebo_ros_control.
[ INFO] [1586376450.501268123, 0.160000000]: Starting plugin DiffDrive(ns = /robot1//)
[ WARN] [1586376450.501280363, 0.160000000]: DiffDrive(ns = /robot1//): missing <rosDebugLevel> default is na
[ INFO] [1586376450.501542681, 0.160000000]: DiffDrive(ns = /robot1//): <tf_prefix> = /robot1
[ WARN] [1586376450.501557371, 0.160000000]: DiffDrive(ns = /robot1//): missing <publishWheelTF> default is false
[ WARN] [1586376450.501566141, 0.160000000]: DiffDrive(ns = /robot1//): missing <publishOdomTF> default is true
[ WARN] [1586376450.501574681, 0.160000000]: DiffDrive(ns = /robot1//): missing <publishWheelJointState> default is false
[ WARN] [1586376450.501601761, 0.160000000]: DiffDrive(ns = /robot1//): missing <wheelAcceleration> default is 0
[ WARN] [1586376450.501618231, 0.160000000]: DiffDrive(ns = /robot1//): missing <wheelTorque> default is 5
[ WARN] [1586376450.501641371, 0.160000000]: DiffDrive(ns = /robot1//): missing <odometrySource> default is 1
[ WARN] [1586376450.501666040, 0.160000000]: GazeboRosDiffDrive Plugin (ns = ) missing <publishTf>, defaults to 1
[ INFO] [1586376450.501699250, 0.160000000]: DiffDrive(ns = /robot1//): Try to subscribe to p3dx/cmd_vel
[ INFO] [1586376450.502694124, 0.160000000]: DiffDrive(ns = /robot1//): Subscribe to p3dx/cmd_vel
[ INFO] [1586376450.502944102, 0.160000000]: DiffDrive(ns = /robot1//): Advertise odom on odom 
[robot1/spawn_robot-4] process has finished cleanly
log file: /home/claude/.ros/log/7c5857da-79d4-11ea-93a2-00d861a1ed1d/robot1-spawn_robot-4*.log`

You can see there are three out of four robot complained repeated advertised services.

Anyway, I still can see all four robots in Gazebo.

There is no error out of motionplanner.launch file. This is the output from it, I am not sure whether this is the correct motion planning.
![image](https://user-images.githubusercontent.com/43088344/78829669-6f51d500-79ef-11ea-95c7-b0534ad49036.png)

But the main problem is what Gazebo showed.
I can see the dynamic object robot moving as the demo video, but the other three robots stayed still all the time.(There are some tiny self-rotatation, but no translation as at all) Like this:
![Screenshot from 2020-04-08 23-17-43](https://user-images.githubusercontent.com/43088344/78829941-e12a1e80-79ef-11ea-9d45-a6c409db9dfd.png)

May I ask what the reason of this? Is it because the errors Gazebo reflected? Is the output from motionplanner.launch correct?

Thanks

**Comment by timmercy** [comment]
The message Invalid_Option when updating the motion trajectory seems to indicate that you have set the linear solver to ma57 while it is not installed, could you check this? 
An example of how this linear solver is set can be found here: https://github.com/meco-group/omg-tools/blob/b7770ae4ba4ba098f7a0b1f702f5b8a70a60e09c/examples/p2p_agv.py#L43

You can remove this line or replace ma57 by mumps.

**Comment by Claud1234** [comment]
> The message Invalid_Option when updating the motion trajectory seems to indicate that you have set the linear solver to ma57 while it is not installed, could you check this?
> An example of how this linear solver is set can be found here:
> 
> https://github.com/meco-group/omg-tools/blob/b7770ae4ba4ba098f7a0b1f702f5b8a70a60e09c/examples/p2p_agv.py#L43
> 
> You can remove this line or replace ma57 by mumps.

Hi:
Thanks for reply.
You are right that there is no 'ma57' library in my machine. It complains when I run the file p2p_agv.py
![image](https://user-images.githubusercontent.com/43088344/78888260-f2177600-7a69-11ea-9b77-40615f8706c5.png)

I changed the line 43 from 'ma57' to 'mumps', looks like this file is run-able.
![image](https://user-images.githubusercontent.com/43088344/78888345-1d9a6080-7a6a-11ea-84ed-72edbb042c6c.png)

So i go back to this two lines https://github.com/meco-group/omg-tools/blob/b7770ae4ba4ba098f7a0b1f702f5b8a70a60e09c/examples/ros_example/src/p3dx_motionplanner/src/motionplanner.py#L77
https://github.com/meco-group/omg-tools/blob/b7770ae4ba4ba098f7a0b1f702f5b8a70a60e09c/examples/ros_example/src/p3dx_motionplanner/src/motionplanner.py#L82

Change the 'ma57' to 'mumps'. Now there is effective result out of motionplanner.py and there is also the translation for that three robots.

But the problem is that three robots running very slow. If you have seen the demo video. There should be a collision for all four robots in the middle of the process, like this:
![image](https://user-images.githubusercontent.com/43088344/78891531-6c4af900-7a70-11ea-898e-49b325f3ffc4.png)

But to me, that three robots running very slow.
![image](https://user-images.githubusercontent.com/43088344/78891614-93092f80-7a70-11ea-9be3-4703912cf5ef.png)
![image](https://user-images.githubusercontent.com/43088344/78891659-a61bff80-7a70-11ea-99fe-0bd929306d6f.png)

May I ask is this because 'mumps' works worse than the 'ma57'. Any other things affect the efficiency ? 

Thanks in advance.

**Comment by Claud1234** [comment]
Okay. I will reflect my own issue. Actually the reason it works slow just because I run this thing in an antique computer. After I solved the compatibility issue with the ROS Melodic and Gazebo 9, 'mumps' also works as good as template video in another powerful computer.

Still have another puzzle. Is this 'ma57' works better than the 'mumps'? I had the problems to install 'ma57' library, both apt and pip have problems. Any recommendation about how to install this library?

Thanks

**Comment by rubenvanparys** [comment]
Hi Claud,
Ma57 is faster than mumps. They're both solvers for linear equations, which will give the same result.
I used to install mumps as part of the HSL solvers, by building them from source. You can follow the instructions here: https://github.com/casadi/casadi/wiki/Obtaining-HSL (https://link.getmailspring.com/link/BD695D76-C17E-49B5-BF62-72B25742E0D5@getmailspring.com/0?redirect=https%3A%2F%2Fgithub.com%2Fcasadi%2Fcasadi%2Fwiki%2FObtaining-HSL&recipient=cmVwbHkrQURRNzU1T1VFRUdHTzJYM1lMSEFOTE40VE5HRU5FVkJOSEhCUEM0Nlc0QHJlcGx5LmdpdGh1Yi5jb20%3D)
Ruben
