### ISSUE TITLE
How to install HSL with omg-tools(I have got the source code)

### ISSUE THREAD

**Issue by wanghuohuo0716** [meco-group/omg-tools#78]
I have got both share files and source code of HSL(Academic License),How should I install them and How to use them in omg-tools?

**Comment by rubenvanparys** [comment]
Hi, installation instructions and instructions to make Ipopt (the nonlinear solver) see the HSL solvers: https://github.com/casadi/casadi/wiki/Obtaining-HSL
In order to use them, you do something similar as in https://github.com/meco-group/omg-tools/blob/b7770ae4ba4ba098f7a0b1f702f5b8a70a60e09c/examples/p2p_agv.py#L43

**Comment by wanghuohuo0716** [comment]
Thanks！
