### ISSUE TITLE
Distributed problems

### ISSUE THREAD

**Issue by EnricaSo** [meco-group/omg-tools#89]
Hello!

I have an issue with understanding how to distribute the ADMM problem on multiple computers/robots. If I understand correctly, in the `compare_distributed_vs_central_quadrotors.py` example (and all other distributed examples), the formulation of the problem is distributed, but the code is implemented in a central way: there is one single problem at the root layer. Also, in the `ros_example`, I understood that all the computation happens on the pc and then commands are published on some topics that the robots are listening to. Is that correct? 

Thanks,
Enrica

**Comment by rubenvanparys** [comment]
Yes that's correct. There is however alsof the 'export' functionality. This
allows to generate C bindings for a single agent, in order to run it truly
distributed (as in the example videos with the autonomous vehicles). In
Python, all distributed control examples are simulated in a central way.

Op di 1 sep. 2020 17:08 schreef Enrica <notifications@github.com>:
